const MESSAGES = {
  COMMANDES: {
    ADMIN: {
      BUTTON: {
        name: "button",
        aliases: ['button'],
        category: 'admin',
        description: "commande test pour les boutons discord",
        usage: '',
        admin: true,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      CONFIG: {
        name: "config",
        aliases: ['config'],
        category: 'admin',
        description: "Modifie la base de donnée.",
        usage: '<clé à modifier> <valeurs>',
        admin: true,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      EVAL: {
        name: "eval",
        aliases: ['eval'],
        category: 'admin',
        description: "Envoi le résultat d'un code javascript testé.",
        usage: '<code à tester>',
        admin: true,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      RELOAD: {
        name: "reload",
        aliases: ['reload','reloads', 'restart'],
        category: 'admin',
        description: "Redémarre le bot.",
        usage: '',
        admin: true,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      SAY: {
        name: "say",
        aliases: ['say','repeat', 'rep'],
        category: 'admin',
        description: "Permet au staff de faire parler le bot n'importe où !",
        usage: '<#salon-de-destination> <message>',
        admin: true,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      ADDROLEEVERYONE: {
        name: "addroleeveryone",
        aliases: ['addroleeveryone', 'addall', 'roleall'],
        category: 'admin',
        description: "Commande pour ajouter des roles à TOUS les membres du discord",
        usage: '',
        admin: true,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
    },
    COOL: {
      EIGHTBALL: {
        name: "8ball",
        aliases: ['8ball', 'question', 'ask'],
        category: 'cool',
        description: "Pose une question au bot et il te répond.",
        usage: '<question>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 10,//temps en secondes
      },
      BOTINFOS: {
        name: "botinfos",
        aliases: ['botinfos', 'bot'],
        category: 'cool',
        description: "Envoi des infos sur le bot.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 10,//temps en secondes
      },
      COULEURS: {
        name: "couleurs",
        aliases: ['couleurs', 'couleur', 'colors', 'color'],
        category: 'cool',
        description: "Envoi un embed qui répertorie toutes les manière d'écrire des textes colorés sur discord.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 10,//temps en secondes
      },
      DICE: {
        name: "dice",
        aliases: ['dice', 'dé', 'de'],
        category: 'cool',
        description: "Lance 6 dés et affiche les 6 chiffres obtenus + le total.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 10,//temps en secondes
      },
      MATH: {
        name: "math",
        aliases: ['math','calcul','calc'],
        category: 'cool',
        description: "Permet de faire toutes sortes de calculs mathématiques (additions, matrices, dérivées, géométrie, etc.).",
        usage: '<calcul>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      PING: {
        name: "ping",
        aliases: ['ping'],
        category: 'cool',
        description: "Répond au message ping par pong, pour tester la rapidité du bot et le temps de réponse de l'API.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      POLL: {
        name: "poll",
        aliases: ['poll', 'sondage'],
        category: 'cool',
        description: "Envoi un embed de sondage avec les réactions pour voter.",
        usage: '<sondage>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: false,
        pollcommand: true,
        cooldown: 0,//temps en secondes
      },
      SERVERINFOS: {
        name: "serverinfos",
        aliases: ['serverinfos', 'serv', 'serveurinfos', 'servinfos', 'server', 'serveur'],
        category: 'cool',
        description: "Envoi des infos à propos du serveur.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 60,//temps en secondes
      },
      SLOTS: {
        name: "slots",
        aliases: ['slots', 'slot'],
        category: 'cool',
        description: "Lance un tirage random pour afficher une grille de 3x3 avec des fruits, le but est d'obtenir 1 ligne ou 1 colonne ou 1 diagonale avec le même fruit pour gagner.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 5,//temps en secondes
      },
      STATISTIQUES: {
        name: "statistiques",
        aliases: ['statistiques', 'stats', 'user', 'userinfos'],
        category: 'cool',
        description: "Envoi des statistiques sur un membre mentionné ou sur la personne qui as fait la commande.",
        usage: '<@membre>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 10,//temps en secondes
      },
      STATUS: {
        name: "status",
        aliases: ['status'],
        category: 'cool',
        description: "Envoi le nombre de membres correspondant à chaque status (online, offline, dnd, idle).",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 60,//temps en secondes
      },
      TEXTES: {
        name: "textes",
        aliases: ['textes', 'txt', 'texte', 'txts', 'text'],
        category: 'cool',
        description: "Envoi un embed qui répertorie toutes les manière d'écrire des textes sur discord (souligné, barré, italique, etc.).",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 60,//temps en secondes
      },
    },
    EXPÉRIENCE: {
      ADDEXPERIENCE: {
        name: "addexperience",
        aliases: ['addexperience', 'addexp', 'addxp'],
        category: 'expérience',
        description: "Ajoute de l'expérience à un membre.",
        usage: '<@membre> <exp à ajouter>',
        admin: true,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      LEADERBOARD: {
        name: "leaderboard",
        aliases: ['leaderboard', 'classement', 'leadexp', 'leadxp','lb'],
        category: 'expérience',
        description: "Affiche le top 10 des membres du serveur (expérience).",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 60,//temps en secondes
      },
      REMOVEEXPERIENCE: {
        name: "removeexperience",
        aliases: ['removeexperience', 'removeexp', 'removexp'],
        category: 'expérience',
        description: "Enlève de l'expérience à un membre.",
        usage: '<@membre> <exp à enlever>',
        admin: true,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      USEREXPERIENCE: {
        name: "userexperience",
        aliases: ['userexperience', 'uexp', 'uxp', 'xp', 'userxp','level','lvl', 'rank'],
        category: 'expérience',
        description: "Envoi les infos d'expérience de l'auteur du message ou du membre mentionné.",
        usage: '<@membre>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 60,//temps en secondes
      },
    },
    MODÉRATION: {
      BAN: {
        name: "ban",
        aliases: ['ban'],
        category: 'modération',
        description: "Ban un membre du serveur.",
        usage: '<@membre> <raison>',
        admin: false,
        modo: false,
        ban: true,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: true,
        isUserModo: true,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      CLEAR: {
        name: "clear",
        aliases: ['clear', 'clean'],
        category: 'modération',
        description: "Supprime un nombre de messages spécifié.",
        usage: '<nombre de messages à supprimer (entre 1 et 100)>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: true,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      CLEARWARNS: {
        name: "clearwarns",
        aliases: ['clearwarns'],
        category: 'modération',
        description: "Supprime tous les avertissements d'un membre.",
        usage: '<@membre>',
        admin: false,
        modo: false,
        ban: false,
        mute: true,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      EMBEDBUILDER: {
        name: "embedbuilder",
        aliases: ['embedbuilder','eb'],
        category: 'modération',
        description: "Créé un embed au fur et à mesure...puis l'envoi",
        usage: '',
        admin: false,
        modo: true,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      INVITES: {
        name: "invites",
        aliases: ['invites'],
        category: 'modération',
        description: "Affiche les invites du serveur",
        usage: '',
        admin: false,
        modo: true,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      KICK: {
        name: "kick",
        aliases: ['kick'],
        category: 'modération',
        description: "Kick un membre du serveur.",
        usage: '<@membre>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: true,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: true,
        isUserModo: true,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      MEMBRES: {
        name: "membres",
        aliases: ['membres', 'member', 'members', 'membre'],
        category: 'modération',
        description: "Envoi un message d'annonce pour que les membres choississent leur genre et puissent accéder au serveur.",
        usage: '',
        admin: false,
        modo: true,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      MUTE: {
        name: "mute",
        aliases: ['mute'],
        category: 'modération',
        description: "Mute un membre du serveur pendant un temps donné.",
        usage: '<@membre> <temps (2s / 5h / 2d / etc.)>',
        admin: false,
        modo: false,
        ban: false,
        mute: true,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: true,
        isUserModo: true,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      PRUNE: {
        name: "prune",
        aliases: ['prune'],
        category: 'modération',
        description: "Supprime un nombre de messages spécifié écrient par un membre spécifié.",
        usage: '<@membre> <nombre de messages à supprimer (entre 1 et 100)>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: true,
        dj: false,
        args: true,
        isUserAdmin: true,
        isUserModo: true,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      RECLAM: {
        name: "reclam",
        aliases: ['reclam'],
        category: 'modération',
        description: "Envoi un embed dans le salon #réclams avec une réaction pour que les membres puissent réagir et ouvre un salon de réclam pour parler en privé avec les admins et/ou les modos si ils ont un soucis sur le serveur MaxCraft.",
        usage: '',
        admin: false,
        modo: true,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      ROLES: {
        name: "roles",
        aliases: ['roles', 'r'],
        category: 'modération',
        description: "Envoi les embeds nécéssaires pour tous les channels permettant de demander des rôles avec les réactions.",
        usage: '',
        admin: false,
        modo: true,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      TICKET: {
        name: "ticket",
        aliases: ['ticket'],
        category: 'modération',
        description: "Envoi un embed dans le salon #demande-de-privé avec une réaction pour que les membres puissent réagir et ouvre un salon ticket pour parler en privé avec les admins et/ou les modos.",
        usage: '',
        admin: false,
        modo: true,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      UNBAN: {
        name: "unban",
        aliases: ['unban'],
        category: 'modération',
        description: "Unban le membre identifié.",
        usage: '<id du membre>',
        admin: false,
        modo: false,
        ban: true,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      UNMUTE: {
        name: "unmute",
        aliases: ['unmute'],
        category: 'modération',
        description: "Unmute le membre mentionné.",
        usage: '<@membre>',
        admin: false,
        modo: false,
        ban: false,
        mute: true,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      UNWARN: {
        name: "unwarn",
        aliases: ['unwarn'],
        category: 'modération',
        description: "Enlève l'avertissement le plus ancien du membre mentionné.",
        usage: '<@membre>',
        admin: false,
        modo: false,
        ban: false,
        mute: true,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      WARN: {
        name: "warn",
        aliases: ['warn'],
        category: 'modération',
        description: "Envoi un avertissement au membre mentionné.",
        usage: '<@membre> <raison>',
        admin: false,
        modo: false,
        modo: false,
        ban: false,
        mute: true,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: true,
        isUserModo: true,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
      WARNS: {
        name: "warns",
        aliases: ['warns'],
        category: 'modération',
        description: "Voir les warns du membre mentionné",
        usage: '<@membre>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 30,//temps en secondes
      },
    },
    MUSIQUE: {
      CLEARQUEUE: {
        name: "clearqueue",
        aliases: ['clearqueue'],
        category: 'musique',
        description: "Efface toutes les musiques présentes dans la liste de lecture.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      FILTER: {
        name: "filter",
        aliases: ['filter'],
        category: 'musique',
        description: "Ajoute un filtre sur la musique, liste des filtres disponibles dans un message épinglé dans le salon #commandes-musique.",
        usage: '<nom du filtre> (liste des filtres disponible avec la commande /filters)',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      FILTERS: {
        name: "filters",
        aliases: ['filters'],
        category: 'musique',
        description: "Liste des filtres disponibles + leur état d'activation.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 10,//temps en secondes
      },
      LOOP: {
        name: "loop",
        aliases: ['loop'],
        category: 'musique',
        description: "Active ou désactive la lecture en boucle de la musique en cours.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      LOOPQUEUE: {
        name: "loopqueue",
        aliases: ['loopqueue'],
        category: 'musique',
        description: "Active ou désactive la lecture en boucle de la liste de lecture.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      NP: {
        name: "np",
        aliases: ['np'],
        category: 'musique',
        description: "Affiche les infos sur la musique jouée actuellement (artiste, vues, temps, etc.).",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      PAUSE: {
        name: "pause",
        aliases: ['pause'],
        category: 'musique',
        description: "Met en pause la musique jouée actuellement.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      PLAY: {
        name: "play",
        aliases: ['play'],
        category: 'musique',
        description: "Recherche une musique sur YouTube et joue le premier résultat de la recherche.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      QUEUE: {
        name: "queue",
        aliases: ['queue'],
        category: 'musique',
        description: "Affiche la liste des musiques présente dans la liste de lecture.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      RESUME: {
        name: "resume",
        aliases: ['resume'],
        category: 'musique',
        description: "Remet la lecture en route pour la musique actuellement en pause.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      SHUFFLE: {
        name: "shuffle",
        aliases: ['shuffle'],
        category: 'musique',
        description: "Mélange dans un ordre aléatoire la liste de lecture.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      SKIP: {
        name: "skip",
        aliases: ['skip'],
        category: 'musique',
        description: "Stop la musique actuelle et passe à la suivante.",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      STOP: {
        name: "stop",
        aliases: ['stop','leave'],
        category: 'musique',
        description: "Arrête la musique actuelle et le bot quitte le salon vocal (attention, toute la liste de lecture actuelle sera supprimée).",
        usage: '',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
      VOLUME: {
        name: "volume",
        aliases: ['volume', 'vol'],
        category: 'musique',
        description: "Change le volume de la musique entre 1 et 100 %.",
        usage: '<valeur du volume souhaité (entre 1 et 100)>',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: true,
        args: true,
        isUserAdmin: false,
        isUserModo: false,
        command: false,
        musiccommand: true,
        cooldown: 0,//temps en secondes
      },
    },
    UTILITAIRES: {
      HELP: {
        name: "help",
        aliases: ['help', 'aide'],
        category: 'utilitaires',
        description: "Envoi la liste des commandes disponibles et les infos pour utiliser correctement chaque commande.",
        usage: '<nom de la commande> (pour plus d\'infos sur une certaine commande)',
        admin: false,
        modo: false,
        ban: false,
        mute: false,
        kick: false,
        managemessages: false,
        dj: false,
        args: false,
        isUserAdmin: false,
        isUserModo: false,
        command: true,
        musiccommand: false,
        cooldown: 0,//temps en secondes
      },
    },

  },
}

exports.MESSAGES = MESSAGES;




//usage: '',
//admin: false,
//ban: false,
//mute: false,
//managemessages: false,
//dj: false,
//args: false,
//isUserAdmin: false,
//isUserModo: false,
//cooldown: 0,//temps en secondes